### ISSUE TITLE
Support Docker-Compose Version 2 Syntax

### ISSUE THREAD

**Issue by apeschel** [zuazo/dockerspec#1]
Hello,

This project is excellent work, and much apprecaited!

The docker-compose tools currently only support version 1 of the docker-compose config. It would be a nice addition to get it working with the version 2 docker-compose config. I'm trying to figure out what the blockers are to provide assitance, please let me know how I can help!

**Comment by zuazo** [comment]
Thanks @apeschel,

I see you're working on it here: https://github.com/mauricioklein/docker-compose-api/pull/26

I going to leave this issue open until the other is completed. Just in case we need to do something about it in this gem. Maybe a version upgrade or something like that.

**Comment by zuazo** [comment]
Version `2` support has been released in [`docker-compose-api` gem version `1.1.1`](https://github.com/mauricioklein/docker-compose-api/releases/tag/v1.1.1).

Closing this.
